import { ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
import { fonts } from "./config/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "FOSO Test",
  description: "Generated by create next app",
  openGraph: {
    images: "/public/TCN_LOGO.png",
    title: "FOSO Test",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"></meta>
      <head>
        <ThemeModeScript />
      </head>
      <body className={fonts.raleWay.variable}>{children}</body>
    </html>
  );
}
